USE IQVIA_IC

--4.	Monte um script SQL que retorne qual grade de produtos menos vendeu (por unidade) no ano de 2018.
--a.	O resultado deve conter as colunas:
--i.	Código da grade de produtos;
--ii.	Quantidade vendida;


SELECT TOP 1
GRAD.CODIGO_GRADE,
SUM(VEN.QUANTIDADE) QUANTIDADE_VENDIDA_POR_GRADE
FROM [IQVIA_IC].[dbo].[PRODUTO] PROD
LEFT JOIN [IQVIA_IC].[dbo].[PRODUTO_PRECO] PREC ON PREC.ID_PRODUTO = PROD.ID_PRODUTO
LEFT JOIN [IQVIA_IC].[dbo].[PRODUTO_GRADE] GRAD ON PREC.ID_PRODUTO = GRAD.ID_PRODUTO
LEFT JOIN [IQVIA_IC].[dbo].[VENDA] VEN ON VEN.ID_PRODUTO = GRAD.ID_PRODUTO
WHERE CONVERT(VARCHAR(4),VEN.PERIODO,112) = '2018'
GROUP BY GRAD.CODIGO_GRADE
ORDER BY SUM(VEN.QUANTIDADE)